"""
Importable parameters for the monte-carlo retirement simulation
"""

DETERMINISTIC = False
INITIAL_WEALTH = 1000000
TARGET_SUCCESS_RATE = 0.85
WITHDRAWAL_UPPER_LIMIT = INITIAL_WEALTH * 0.10
WITHDRAWAL_LOWER_LIMIT = INITIAL_WEALTH * 0.00
AVERAGE_RETURN = 0.06
STD_RETURN = 0.09
INFLATION_RATE = 0.025
STD_INFLATION = 0.015
NUM_RUNS = 50
NUM_YEARS = 1